node {
    // define the secrets and the env variables
    // engine version can be defined on secret, job, folder or global.
    // the default is engine version 2 unless otherwise specified globally.
    def secrets = [
        [path: 'kv-v2/devops-secret/team-10', engineVersion: 2, secretValues: [
            [envVar: 'testing', vaultKey: 'username'],
            [envVar: 'testing_again', vaultKey: 'password']]],
    ]

    // optional configuration, if you do not provide this the next higher configuration
    // (e.g. folder or global) will be used
    def configuration = [vaultUrl: 'http://192.168.247.135:8200',
                         vaultCredentialId: 'vault-app-role',
                         engineVersion: 1]
    // inside this block your credentials will be available as env variables
    withVault([configuration: configuration, vaultSecrets: secrets]) {
        sh 'echo $testing|tee testing.txt'
        sh 'export TESTING=$testing'
        sh 'cat testing.txt'
        sh 'echo "hello \n world" > hello_world.txt'
        sh 'echo $testing >> hello_world.txt'
        sh 'cat hello_world.txt'
        sh 'echo $testing_again|tee testing_again.txt'
        sh 'cat testing_again.txt'
    }
}
